#!/bin/sh

ICECAST_ADMIN_USERNAME=${ICECAST_ADMIN_USERNAME:-admin}
ICECAST_ADMIN_EMAIL=${ICECAST_ADMIN_EMAIL:-none}
ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD:-admin}
ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD:-admin}
ICECAST_RELAY_PASSWORD=${ICECAST_RELAY_PASSWORD:-admin}
ICECAST_LOCATION=${ICECAST_LOCATION:-MilkyWay}
ICECAST_HOSTNAME=${ICECAST_HOSTNAME:-Pluto}
ICECAST_PORT=${ICECAST_PORT:-8000}
ICECAST_MAX_CLIENTS=${ICECAST_MAX_CLIENTS:-100}
ICECAST_MAX_SOURCES=${ICECAST_MAX_SOURCES:-100}

envsubst < /icecast.tmpl > /etc/icecast.xml

icecast -c /etc/icecast.xml
